project:
  type: website
  output-dir: docs
  
website:
  title: "Go_Younha"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hw1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



