project:
  type: website
  output-dir: docs
  
website:
  title: "Go_Younha"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts/index.qmd
        text: Blog
        
format:
  html:
    theme: cosmos
    toc: true



