project:
  type: website
  output-dir: docs
  
website:
  title: "Go_Younha"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: about
      - href: homework1.qmd
        text: homework1
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



